version: '3'
services:
  keycloak:
    image: jboss/keycloak:7.0.1
    container_name: keycloak
    command: ["-Djboss.socket.binding.port-offset=0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/opt/jboss/keycloak/bin/config -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"]
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./restaurant/:/opt/jboss/keycloak/themes/restaurant
      - ./config:/opt/jboss/keycloak/bin/config
